import { describe, it, expect } from "bun:test";
import {
  resolveWebSettings,
  buildTtydArgs,
  generateCredential,
  dependencyInstallHint,
  type WebOptions,
} from "../web";
import type { WebConfig } from "../config";
import type { ClaudeInvocation } from "../launcher";

const invocation: ClaudeInvocation = {
  cmd: "claude",
  finalArgs: ["--bare", "--model", "gpt-4o"],
};

describe("resolveWebSettings", () => {
  it("uses built-in defaults when nothing is set", () => {
    const s = resolveWebSettings({});
    expect(s.host).toBe("0.0.0.0");
    expect(s.port).toBe(7681);
    expect(s.autoGenerated).toBe(true);
    expect(s.auth).toMatch(/^claude:/);
    expect(s.noAuth).toBe(false);
  });

  it("prefers CLI flag over config over default (host/port)", () => {
    const config: WebConfig = { host: "127.0.0.1", port: 9000 };
    const opts: WebOptions = { host: "10.0.0.5" };
    const s = resolveWebSettings(opts, config);
    expect(s.host).toBe("10.0.0.5"); // flag wins
    expect(s.port).toBe(9000); // config wins over default
  });

  it("uses explicit auth without auto-generating", () => {
    const s = resolveWebSettings({ auth: "alice:secret" });
    expect(s.auth).toBe("alice:secret");
    expect(s.autoGenerated).toBe(false);
  });

  it("uses config.auth when no flag given", () => {
    const config: WebConfig = { auth: "$WEB_PASS" };
    const s = resolveWebSettings({}, config);
    expect(s.auth).toBe("$WEB_PASS");
    expect(s.autoGenerated).toBe(false);
  });

  it("noAuth disables auth and skips auto-generation", () => {
    const s = resolveWebSettings({ noAuth: true });
    expect(s.auth).toBeUndefined();
    expect(s.noAuth).toBe(true);
  });

  it("resolves fontSize with flag > config precedence", () => {
    expect(resolveWebSettings({}).fontSize).toBeUndefined();
    expect(resolveWebSettings({}, { font_size: 18 }).fontSize).toBe(18);
    expect(resolveWebSettings({ fontSize: 22 }, { font_size: 18 }).fontSize).toBe(22);
  });
});

describe("buildTtydArgs", () => {
  it("includes -W, -p, and the trailing tmux command", () => {
    const settings = resolveWebSettings({}); // default host, auto auth
    const args = buildTtydArgs(settings, "openai", invocation);
    expect(args[0]).toBe("-W");
    expect(args).toContain("-p");
    expect(args).toContain("7681");
    expect(args).toContain("tmux");
    expect(args).toContain("-L");
    expect(args).toContain("claude-wrap-openai");
    expect(args).toContain("new-session");
    expect(args).toContain("-A");
    expect(args).toContain("-s");
    expect(args).toContain("main");
    // command tail
    const idx = args.indexOf("claude");
    expect(args.slice(idx)).toEqual(["claude", "--bare", "--model", "gpt-4o"]);
  });

  it("adds -c only when auth is set", () => {
    const noAuth = buildTtydArgs(resolveWebSettings({ noAuth: true }), "p", invocation);
    expect(noAuth).not.toContain("-c");

    const withAuth = buildTtydArgs(
      resolveWebSettings({ auth: "u:p" }),
      "p",
      invocation,
    );
    const cIdx = withAuth.indexOf("-c");
    expect(cIdx).toBeGreaterThan(-1);
    expect(withAuth[cIdx + 1]).toBe("u:p");
  });

  it("omits -i for the all-interfaces default 0.0.0.0", () => {
    const args = buildTtydArgs(resolveWebSettings({}), "p", invocation);
    expect(args).not.toContain("-i");
  });

  it("adds -i for a restricted host", () => {
    const args = buildTtydArgs(
      resolveWebSettings({ host: "127.0.0.1" }),
      "p",
      invocation,
    );
    const iIdx = args.indexOf("-i");
    expect(iIdx).toBeGreaterThan(-1);
    expect(args[iIdx + 1]).toBe("127.0.0.1");
  });

  it("adds -C/-K only when both TLS paths are present", () => {
    const none = buildTtydArgs(
      resolveWebSettings({ tlsCert: "/a.crt" }),
      "p",
      invocation,
    );
    expect(none).not.toContain("-C");

    const both = buildTtydArgs(
      resolveWebSettings({ tlsCert: "/a.crt", tlsKey: "/a.key" }),
      "p",
      invocation,
    );
    expect(both).toContain("-C");
    expect(both).toContain("/a.crt");
    expect(both).toContain("-K");
    expect(both).toContain("/a.key");
  });

  it("omits -t fontSize when no font size is set", () => {
    const args = buildTtydArgs(resolveWebSettings({}), "p", invocation);
    expect(args).not.toContain("-t");
  });

  it("adds -t fontSize=<n> when a font size is set", () => {
    const args = buildTtydArgs(
      resolveWebSettings({ fontSize: 20 }),
      "p",
      invocation,
    );
    const tIdx = args.indexOf("-t");
    expect(tIdx).toBeGreaterThan(-1);
    expect(args[tIdx + 1]).toBe("fontSize=20");
  });
});

describe("generateCredential", () => {
  it("returns a claude: prefixed non-empty password", () => {
    const c = generateCredential();
    expect(c.startsWith("claude:")).toBe(true);
    expect(c.length).toBeGreaterThan("claude:".length);
  });

  it("produces distinct values across calls", () => {
    expect(generateCredential()).not.toBe(generateCredential());
  });
});

describe("dependencyInstallHint", () => {
  it("returns a brew hint on darwin", () => {
    expect(dependencyInstallHint("darwin")).toContain("brew install tmux ttyd");
  });

  it("returns an apt hint on linux", () => {
    const out = dependencyInstallHint("linux");
    expect(out).toContain("apt-get");
    expect(out).toContain("ttyd");
  });

  it("returns generic instructions on unknown platforms", () => {
    expect(dependencyInstallHint("win32")).toContain("tmux");
  });
});
