import { spawn, spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import type { Config, WebConfig } from "./config";
import { buildClaudeInvocation, type ClaudeInvocation } from "./launcher";
import { resolveVar } from "./env";
import { isWsl } from "./platform";

export interface WebOptions {
  host?: string;
  port?: number;
  auth?: string;
  tlsCert?: string;
  tlsKey?: string;
  noAuth?: boolean;
  fontSize?: number;
}

export interface ResolvedWebSettings {
  host: string;
  port: number;
  auth?: string; // "user:pass"; undefined means no authentication
  tlsCert?: string;
  tlsKey?: string;
  noAuth: boolean;
  autoGenerated: boolean;
  fontSize?: number;
}

const DEFAULT_HOST = "0.0.0.0";
const DEFAULT_PORT = 7681;

// Precedence: explicit CLI flag > config.web > built-in default.
// `auth` may be a literal "user:pass" or a "$VAR" reference (resolved later
// in runWeb); this helper stays pure and just picks the raw string.
export function resolveWebSettings(
  opts: WebOptions,
  config?: WebConfig,
): ResolvedWebSettings {
  const host = opts.host ?? config?.host ?? DEFAULT_HOST;
  const port = opts.port ?? config?.port ?? DEFAULT_PORT;
  const tlsCert = opts.tlsCert ?? config?.tls_cert;
  const tlsKey = opts.tlsKey ?? config?.tls_key;
  const fontSize = opts.fontSize ?? config?.font_size;

  const noAuth = opts.noAuth ?? false;
  let auth: string | undefined;
  let autoGenerated = false;

  if (!noAuth) {
    const chosen = opts.auth ?? config?.auth;
    if (chosen) {
      auth = chosen;
    } else {
      auth = generateCredential();
      autoGenerated = true;
    }
  }

  return { host, port, auth, tlsCert, tlsKey, noAuth, autoGenerated, fontSize };
}

export function generateCredential(): string {
  const pass = randomBytes(9).toString("base64url");
  return `claude:${pass}`;
}

// Compose the ttyd argv. ttyd options come first, then the command it serves
// (a tmux session). Binding is restricted only when the host isn't the
// all-interfaces default (ttyd already binds 0.0.0.0 by default).
export function buildTtydArgs(
  settings: ResolvedWebSettings,
  presetName: string,
  invocation: ClaudeInvocation,
): string[] {
  const args: string[] = ["-W", "-p", String(settings.port)];

  if (settings.host !== DEFAULT_HOST) {
    args.push("-i", settings.host);
  }
  if (settings.auth) {
    args.push("-c", settings.auth);
  }
  if (settings.tlsCert && settings.tlsKey) {
    args.push("-C", settings.tlsCert, "-K", settings.tlsKey);
  }
  // xterm.js client option: bump font size for readability (e.g. on phones)
  if (settings.fontSize !== undefined) {
    args.push("-t", `fontSize=${settings.fontSize}`);
  }

  const tmuxCmd: string[] = [
    "tmux",
    "-L",
    `claude-wrap-${presetName}`,
    "new-session",
    "-A",
    "-s",
    "main",
    invocation.cmd,
    ...invocation.finalArgs,
  ];

  return [...args, ...tmuxCmd];
}

export function dependencyInstallHint(platform: string): string {
  if (platform === "darwin") {
    return "  brew install tmux ttyd";
  }
  if (platform === "linux") {
    return [
      "  sudo apt-get install -y tmux",
      "  # ttyd is rarely in distro repos; install from a release:",
      "  #   https://github.com/tsl0922/ttyd/releases",
    ].join("\n");
  }
  if (platform === "win32") {
    return [
      "  Native Windows: tmux/ttyd aren't available here. Run claude-wrap under WSL,",
      "  then install there:",
      "    sudo apt-get install -y tmux",
      "    # ttyd: https://github.com/tsl0922/ttyd/releases",
    ].join("\n");
  }
  return [
    "  tmux — https://github.com/tmux/tmux",
    "  ttyd — https://github.com/tsl0922/ttyd/releases",
  ].join("\n");
}

/**
 * `--web` needs tmux + ttyd, which don't run on native Windows. It DOES work
 * under WSL (those tools exist there), so callers should still allow it in
 * WSL. Pure + parameterized for unit testing.
 */
export function webUnsupportedOnNativeWindows(
  platform: string = process.platform,
  wsl: boolean = isWsl(),
): boolean {
  return platform === "win32" && !wsl;
}

function socketFlag(presetName: string): string {
  return `claude-wrap-${presetName}`;
}

export function webDryRun(
  config: Config,
  presetName: string,
  isAnthropic: boolean,
  skipBare: boolean,
  args: string[],
  webOpts: WebOptions,
): string {
  const invocation = buildClaudeInvocation(config, args, isAnthropic, skipBare);
  const settings = resolveWebSettings(webOpts, config.web);
  const ttydArgs = buildTtydArgs(settings, presetName, invocation);
  return [
    `# claude-wrap --web --dry-run`,
    `# Preset: ${presetName}`,
    `# Command: ttyd ${ttydArgs.join(" ")}`,
    "",
  ].join("\n");
}

export async function runWeb(
  config: Config,
  presetName: string,
  envVars: Record<string, string>,
  args: string[],
  isAnthropic: boolean,
  skipBare: boolean,
  webOpts: WebOptions,
): Promise<void> {
  // 0. Platform gate: tmux/ttyd are unavailable on native Windows.
  if (webUnsupportedOnNativeWindows()) {
    process.stderr.write(
      "claude-wrap: --web is not supported on native Windows (it needs tmux + ttyd).\n" +
        "  Run claude-wrap under WSL, or use the terminal launch (`claude-wrap`).\n",
    );
    process.exit(1);
  }

  // 1. Dependency check
  const tmuxOk = spawnSync("which", ["tmux"], { stdio: "pipe" }).status === 0;
  const ttydOk = spawnSync("which", ["ttyd"], { stdio: "pipe" }).status === 0;
  if (!tmuxOk || !ttydOk) {
    process.stderr.write("claude-wrap: --web requires tmux and ttyd.\n");
    if (!tmuxOk) process.stderr.write("  missing: tmux\n");
    if (!ttydOk) process.stderr.write("  missing: ttyd\n");
    process.stderr.write("\n" + dependencyInstallHint(process.platform) + "\n");
    process.exit(1);
  }

  // 2. Resolve settings, then resolve any $VAR references in auth/tls
  const raw = resolveWebSettings(webOpts, config.web);
  const combinedEnv = { ...(process.env as Record<string, string>), ...envVars };

  let auth = raw.auth;
  if (auth) auth = resolveVar(auth, combinedEnv);
  const tlsCert = raw.tlsCert ? resolveVar(raw.tlsCert, combinedEnv) : undefined;
  const tlsKey = raw.tlsKey ? resolveVar(raw.tlsKey, combinedEnv) : undefined;

  const settings: ResolvedWebSettings = { ...raw, auth, tlsCert, tlsKey };

  // 3. Security warnings
  if (raw.noAuth) {
    process.stderr.write(
      "  WARNING: --web-no-auth set — the web terminal has no authentication.\n",
    );
  }
  if (settings.host === DEFAULT_HOST && !settings.auth) {
    process.stderr.write(
      "  WARNING: serving on all interfaces (0.0.0.0) with no authentication.\n",
    );
  }

  // 4. Build claude invocation + ttyd argv
  const invocation = buildClaudeInvocation(config, args, isAnthropic, skipBare);
  const ttydArgs = buildTtydArgs(settings, presetName, invocation);

  // 5. Print URL + credentials
  const scheme = settings.tlsCert && settings.tlsKey ? "https" : "http";
  const displayHost =
    settings.host === DEFAULT_HOST ? "0.0.0.0 (all interfaces)" : settings.host;
  process.stdout.write("claude-wrap web UI\n");
  process.stdout.write(`  Preset: ${presetName}\n`);
  process.stdout.write(`  URL:    ${scheme}://${settings.host}:${settings.port}/\n`);
  process.stdout.write(`  Host:   ${displayHost}\n`);
  if (settings.auth) {
    process.stdout.write(
      `  Auth:   ${settings.autoGenerated ? "(auto-generated) " : ""}${settings.auth}\n`,
    );
  }
  process.stdout.write("\n  Open the URL in a browser. Ctrl-C to stop.\n");

  // 6. Spawn ttyd with the merged ANTHROPIC_* environment. A fresh tmux
  //    socket (-L) starts a dedicated tmux server that inherits this env,
  //    so credentials reach claude via the environment (never argv → no ps
  //    leakage).
  const child = spawn("ttyd", ttydArgs, {
    env: { ...process.env, ...envVars },
    stdio: "inherit",
  });

  // 7. Cleanup: tear down the dedicated tmux server on exit
  const cleanup = (): void => {
    spawnSync(
      "tmux",
      ["-L", socketFlag(presetName), "kill-server"],
      { stdio: "ignore" },
    );
  };

  const onSignal = (): void => {
    cleanup();
    process.exit(130);
  };
  process.on("SIGINT", onSignal);
  process.on("SIGTERM", onSignal);

  child.on("exit", (code, signal) => {
    cleanup();
    if (signal) process.exit(128 + 1);
    process.exit(code ?? 0);
  });
}
